[package]
name = "ray_v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam={version="0.23.0"}
rand="*"
gltf="*"
indicatif="*"
image="*"
serde_json = "1.0"
serde = { version = "1.0"}
bvh="*"