name = "image"

[camera]
mode = "P"
size = [512.0, 512.0]
far = 1000.0
near = 0.01
eye = [0.0, 4.0, 4.0]
target = [0.0, 0.0, 0.0]
up = [0.0, 1.0, 0.0]
fov = 110.0

[[primitive]]
mode = "Shpere"
trans = { r = [1.0, 0.0, 0.0, 0.0], s = [1.0, 1.0, 1.0], t = [1.0, 0.0, 1.0] }
r = 1.0
material_index = 1

[[primitive]]
mode = "Shpere"
trans = { r = [
    0.0,
    0.0,
    1.0,
    0.0,
], s = [
    1.0,
    1.0,
    1.0,
], t = [
    0.0,
    0.0,
    -100.0,
] }
material_index = 0
r = 100.0

[[shapes]]
mode = "Rect"
trans = { r = [1.0, 0.0, 0.0, 0.0], s = [1.0, 1.0, 1.0], t = [0.0, 0.0, 3.0] }
material_index = 0


[[material]]
mode = "Matte"
kd = 0
sigma = 0.0

[[material]]
mode = "Mirror"
kr = 2

[[texture]]
mode = "Constant"
value = [0.7, 0.7, 0.7]

[[texture]]
mode = "Constant"
value = [0.5, 0.7, 1.0]

[[texture]]
mode = "Constant"
value = [0.5, 0.3, 0.3]

[[light]]
mode = "Area"
lemit = [100.0, 100.0, 100.0]
shape_index = 0

#[[light]]
#mode = "Infinite"
#lemit = [10.0, 100.0, 100.0]
#skybox = 1
#world_center = [0.0, 0.0, 0.0]
#world_radius = 10000.0

# [intergator]
# mode = "Path"
# core_num = 7
# sample_num = 10
# q = 0.5
# max_depth = 3
[intergator]
mode = "Direct"
sample_num = 1
core_num = 6
startegy = "UniformOne"
