name = "image"

[camera]
mode = "P"
size = [2048.0, 2048.0]
far = 1000.0
near = 0.01
eye = [0.0, 4.0, 4.0]
target = [0.0, 0.0, 0.0]
up = [0.0, 1.0, 0.0]
fov = 110.0

[[primitive]]
mode = "Rect"
trans = { r = [1.0, 0.0, 0.0, 0.0], s = [6.0, 6.0, 1.0], t = [-3.0, 0.0, 0.0] }
material_index = 0

[[primitive]]
mode = "Rect"
trans = { r = [1.0, 0.0, 0.0, 90.0], s = [8.0, 8.0, 1.0], t = [-3.0, 0.0, 0.0] }
material_index = 0
[[primitive]]
mode = "Rect"
trans = { r = [1.0, 0.0, 0.0, 90.0], s = [8.0, 8.0, 1.0], t = [3.0, 0.0, 0.0] }
material_index = 0
[[primitive]]
mode = "Rect"
trans = { r = [1.0, 0.0, 0.0, 0.0], s = [6.0, 6.0, 1.0], t = [-3.0, 0.0, 8.0] }
material_index = 0

[[primitive]]
mode = "Rect"
trans = { r = [0.0, 1.0, 0.0, 90.0], s = [6.0, 8.0, 1.0], t = [-3.0, -3.0, 8.0] }
material_index = 0

[[shape]]
mode="Rect"
trans



[intergator]
mode = "Path"
core_num = 7
sample_num = 128
q = 0.5
max_depth = 3

