[[shape]]
mode = "Rect"
transform = { r = [1.0, 0.0, 0.0, 0.0], s = [6.0, 6.0, 1.0], t = [-3.0, 0.0, 0.0] }
# right
[[shape]]
mode = "Rect"
transform = { r = [0.0, 1.0, 0.0, -90.0], s = [6.0, 6.0, 1.0], t = [-3.0, 0.0, 0.0] }
## left
[[shape]]
mode = "Rect"
transform = { r = [0.0, 1.0, 0.0, 90.0], s = [6.0, 6.0, 1.0], t = [3.0, 0.0, 6.0] }
#top
[[shape]]
mode = "Rect"
transform = { r = [0.0, 1.0, 0.0, 180.0], s = [6.0, 6.0, 1.0], t = [3.0, 0.0, 6.0] }
##back
[[shape]]
mode = "Rect"
transform = { r = [1.0, 0.0, 0.0, 90.0], s = [6.0, 6.0, 1.0], t = [-3.0, 0.0, 0.0] }

[[shape]]
mode = "Sphere"
transform = { r = [1.0, 0.0, 0.0, 0.0], s = [1.0, 1.0, 1.0], t = [-1.0, 2.0, 4.0] }
r=1.0

[[shape]]
mode = "Sphere"
transform = { r = [1.0, 0.0, 0.0, 0.0], s = [1.0, 1.0, 1.0], t = [1.5, 3.0, 2.0] }
r=1.0

[[shape]]
mode = "Rect"
transform = { r = [1.0, 0.0, 0.0, 180.0], s = [1.0, 1.0, 1.0], t = [-0.5, 3.0, 5.2] }


[[light]]
mode = "Area"
emit = [100.0, 100.0, 100.0]

[[material]]
mode = "Matte"
kd = 0
sigma = 0.0

[[material]]
mode = "Mirror"
kr = 1
sigma = 0.0


[[texture]]
mode = "Constant"
value = [0.7, 0.7, 0.7]

[[texture]]
mode = "Constant"
value = [0.4, 0.8, 0.1]


[[primitive]]
mode = "GeometricPrimitive"
shape_index=0
material_index=0

[[primitive]]
mode = "GeometricPrimitive"
shape_index=1
material_index=0

[[primitive]]
mode = "GeometricPrimitive"
shape_index=2
material_index=0

[[primitive]]
mode = "GeometricPrimitive"
shape_index=3
material_index=0

[[primitive]]
mode = "GeometricPrimitive"
shape_index=4
material_index=0

[[primitive]]
mode = "GeometricPrimitive"
shape_index=5
material_index=0

[[primitive]]
mode = "GeometricPrimitive"
shape_index=6
material_index=0

[[primitive]]
mode = "GeometricPrimitive"
shape_index=7
light_index =0


