[[primitive]]
mode = "Rect"
transform = { r = [1.0, 0.0, 0.0, 0.0], s = [6.0, 6.0, 1.0], t = [-3.0, 0.0, 0.0] }
material_index = 0
# right
[[primitive]]
mode = "Rect"
transform = { r = [0.0, 1.0, 0.0, -90.0], s = [6.0, 6.0, 1.0], t = [-3.0, 0.0, 0.0] }
material_index = 1

## left
[[primitive]]
mode = "Rect"
transform = { r = [0.0, 1.0, 0.0, 90.0], s = [6.0, 6.0, 1.0], t = [3.0, 0.0, 6.0] }
material_index = 2
##top
[[primitive]]
mode = "Rect"
transform = { r = [0.0, 1.0, 0.0, 180.0], s = [6.0, 6.0, 1.0], t = [3.0, 0.0, 6.0] }
material_index = 0
##back
[[primitive]]
mode = "Rect"
transform = { r = [1.0, 0.0, 0.0, 90.0], s = [6.0, 6.0, 1.0], t = [-3.0, 0.0, 0.0] }
material_index = 0

[[primitive]]
mode = "Sphere"
transform = { r = [1.0, 0.0, 0.0, 0.0], s = [1.0, 1.0, 1.0], t = [-1.0, 2.0, 4.0] }
r=1.0
material_index = 3

[[primitive]]
mode = "Sphere"
transform = { r = [1.0, 0.0, 0.0, 0.0], s = [1.0, 1.0, 1.0], t = [1.5, 3.0, 2.0] }
r=1.0
material_index = 4

[[primitive]]
mode = "Rect"
transform = { r = [1.0, 0.0, 0.0, 180.0], s = [1.0, 1.0, 1.0], t = [-0.5, 3.0, 5.9] }
material_index = 0

[[light]]
mode = "Area"
emit = [100.0, 100.0, 100.0]
shape_index = 7

[[material]]
mode = "Matte"
kd = 0
sigma = 0.0

[[material]]
mode = "Matte"
kd = 2
sigma = 0.0

[[material]]
mode = "Matte"
kd = 3
sigma = 0.0

[[material]]
mode = "Mirror"
kr = 1
sigma = 0.0

[[material]]
mode = "Matte"
kd = 2
sigma = 0.0

[[texture]]
mode = "Constant"
value = [0.7, 0.7, 0.7]

[[texture]]
mode = "Constant"
value = [0.4, 0.8, 0.1]


[[texture]]
mode = "Constant"
value = [1.0, 1.0, 1.0]

[[texture]]
mode = "Constant"
value = [1.0, 0.0, 0.0]

[[texture]]
mode = "Constant"
value = [0.0, 1.0, 0.0]


[[texture]]
mode = "Constant"
value = [0.0, 0.0, 1.0]




