[[obj]]
transform = { t = [
    0.0,
    0.0,
    0.0,
], r = [
    0.0,
    0.0,
    0.0,
    1.0,
], s = [
    1.0,
    1.0,
    1.0,
] }
objtype = "gltf"
path = "object/a.gltf"
material_index = 0

[[obj]]
transform = { translation = [
    0.0,
    0.0,
    0.0,
], rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
], scale = [
    1.0,
    1.0,
    1.0,
] }
objtype = "obj"
path = "object/box.obj"
material_index = 0

[[material]]
mode = "Matte"
kd = 0
sigma = 0.0

[[material]]
mode = "Mirror"
kr = 0
sigma = 0.0

[[material]]
mode = "Metal"
eta = 0
k = 0
roughness = 2

[[texture]]
mode = "Constant"
value = [0.7, 0.7, 0.7]

[[texture]]
mode = "Image"
path = "kloofendal_43d_clear_puresky_1k.hdr"

[[texture]]
mode = "Constant"
value = [0.1, 0.1, 0.1]


[[light]]
mode = "Infinite"
world_center = [0.0, 0.0, 0.0]
world_radius = 1000.0
skybox = 1

[[shapes]]
mode = "Rect"
trans = { r = [1.0, 0.0, 0.0, 180.0], s = [1.0, 1.0, 1.0], t = [0.0, 0.0, 1.0] }
material_index = 0

[[light]]
mode = "Area"
lemit = [100.0, 100.0, 100.0]
shape_index = 0