name = "image"
assert = "./file/sence.toml"

[camera]
mode = "P"
size = [512.0, 512.0]
far = 1000.0
near = 0.01
eye = [0.0, 8.0, 4.0]
target = [0.0, -8.0, 0.0]
up = [0.0, 1.0, 0.0]
fov = 110.0

[integrator]
mode = "Path"
core_num = 8
sample_num = 32
q = 0.0
max_depth = 10