[camera]
mode = "P"
size = [1024.0, 1024.0]
far = 1000.0
near = 0.01
[[shapes]]
mode = "Rect"
r = [0.0, 0.0, 0.0, 0.0]
s = [0.0, 0.0, 0.0]
t = [0.0, 0.0, 0.0]
[[shapes]]
mode = "Rect"
r = [0.0, 0.0, 0.0, 0.0]
s = [0.0, 0.0, 0.0]
t = [0.0, 0.0, 0.0]
[[shapes]]
mode = "Shpere"
r = [0.0, 0.0, 0.0, 0.0]
s = [0.0, 0.0, 0.0]
t = [0.0, 0.0, 0.0]
rr = 10.0

[[material]]
mode = "Matte"
value = { mode = "Image", value = "asdsdsad" }
