name = "image"
assert = "./file/light_bank.toml"

[camera]
mode = "P"
size = [512.0, 512.0]
far = 1000.0
near = 0.01
eye = [0.0, 2.0, 5.0]
target = [0.0, 0.0, 0.0]
up = [0.0, 1.0, 0.0]
fov = 110.0

[integrator]
mode = "Path"
core_num = 7
sample_num = 1
q = 0.5
max_depth = 5