name = "image"

[camera]
mode = "P"
size = [2048.0, 2048.0]
far = 1000.0
near = 0.01
eye = [0.0, 5.0, 5.0]
target = [0.0, -8.0, 0.0]
up = [0.0, 1.0, 0.0]
fov = 110.0

[intergator]
mode = "Path"
core_num = 16
sample_num = 16
q = 0.1
max_depth = 3

[[primitive]]
mode = "Rect"
trans = { r = [1.0, 0.0, 0.0, 0.0], s = [6.0, 6.0, 1.0], t = [-3.0, -3.0, 0.0] }
material_index = 1

[[primitive]]
mode = "Shpere"
trans = { r = [1.0, 0.0, 0.0, 0.0], s = [1.0, 1.0, 1.0], t = [-2.0, 0.0, 1.0] }
r=1.0
material_index = 1

[[primitive]]
mode = "Shpere"
trans = { r = [1.0, 0.0, 0.0, 0.0], s = [1.0, 1.0, 1.0], t = [2.0, 0.0, 1.0] }
r=1.0
material_index = 0

[[light]]
mode = "Infinite"
world_center = [0.0, 0.0, 0.0]
world_radius = 10000.0
skybox = 1


[[material]]
mode = "Matte"
kd = 0
sigma = 0.0

[[material]]
mode = "Mirror"
kr = 0
sigma = 0.0


[[texture]]
mode = "Constant"
value = [0.7, 0.7, 0.7]



[[texture]]
mode = "Image"
path = "kloofendal_48d_partly_cloudy_puresky_1k.hdr"

[[texture]]
mode = "Constant"
value = [0.9, 0.8, 0.7]

# [[texture]]
# mode = "Image"
# path = "Cube_BaseColor.png"
