
[[primitive]]
mode = "Rect"
transform = { r = [1.0, 0.0, 0.0, 0.0], s = [6.0, 6.0, 1.0], t = [-3.0, -3.0, 0.0] }
material_index = 1

[[primitive]]
mode = "Sphere"
transform = { r = [1.0, 0.0, 0.0, 0.0], s = [1.0, 1.0, 1.0], t = [0.0, 0.0, 1.2] }
r=1.0
material_index = 2

[[light]]
mode = "Infinite"
world_center = [0.0, 0.0, 0.0]
world_radius = 1000.0
skybox = 1

[[material]]
mode = "Matte"
kd = 0
sigma = 0.0

[[material]]
mode = "Mirror"
kr = 0
sigma = 0.0

[[material]]
mode = "Metal"
eta = 0
k = 0
roughness = 2


[[texture]]
mode = "Constant"
value = [0.7, 0.7, 0.7]


[[texture]]
mode = "Image"
path = "./resource/tree shade.jpg"


[[texture]]
mode = "Constant"
value = [0.1, 0.1, 0.1]
